export const MODALITIES = [
  { code: "ATL", name: "Atletismo", icon: "running" },
  { code: "NAT", name: "Natacao", icon: "waves" },
  { code: "JUD", name: "Judo", icon: "swords" },
  { code: "VEL", name: "Vela", icon: "sailboat" },
  { code: "GIN", name: "Ginastica", icon: "flip-vertical" },
  { code: "BOX", name: "Boxe", icon: "hand-metal" },
  { code: "TEN", name: "Tenis", icon: "circle-dot" },
  { code: "FUT", name: "Futebol", icon: "circle" },
  { code: "BAS", name: "Basquete", icon: "circle" },
  { code: "VOL", name: "Voleibol", icon: "circle" },
  { code: "HAL", name: "Halterofilismo", icon: "dumbbell" },
  { code: "CAN", name: "Canoagem", icon: "ship" },
  { code: "ESG", name: "Esgrima", icon: "swords" },
  { code: "TIR", name: "Tiro Esportivo", icon: "target" },
  { code: "HIP", name: "Hipismo", icon: "horse" },
  { code: "PEN", name: "Pentatlo Moderno", icon: "medal" },
  { code: "TAE", name: "Taekwondo", icon: "hand-metal" },
  { code: "LPE", name: "Levantamento de Peso", icon: "dumbbell" },
  { code: "BDM", name: "Badminton", icon: "feather" },
  { code: "RUG", name: "Rugby", icon: "trophy" },
  { code: "SUR", name: "Surfe", icon: "waves" },
  { code: "ESC", name: "Escalada", icon: "mountain" },
  { code: "SKA", name: "Skate", icon: "zap" },
  { code: "TRM", name: "Trampolim", icon: "arrow-up" },
  { code: "CIC", name: "Ciclismo", icon: "bike" },
  { code: "TRA", name: "Triatlo", icon: "medal" },
  { code: "MAR", name: "Maratona Aquatica", icon: "waves" },
  { code: "GAR", name: "Ginastica Artistica", icon: "star" },
  { code: "POL", name: "Polo Aquatico", icon: "waves" },
  { code: "HAN", name: "Handebol", icon: "circle" },
  { code: "HOC", name: "Hoquei", icon: "stick" },
  { code: "TIE", name: "Tiro com Arco", icon: "target" },
  { code: "GOL", name: "Golfe", icon: "flag" },
  { code: "KAR", name: "Karate", icon: "hand-metal" },
  { code: "BRE", name: "Breaking", icon: "music" },
  { code: "REM", name: "Remo", icon: "ship" },
  { code: "LUT", name: "Luta", icon: "swords" },
  { code: "NAS", name: "Nado Artistico", icon: "waves" },
  { code: "SAG", name: "Saltos Ornamentais", icon: "arrow-down" },
  { code: "TEM", name: "Tenis de Mesa", icon: "circle-dot" },
] as const;

export type ModalityCode = (typeof MODALITIES)[number]["code"];
